-- quotes table (quote calculator data)
CREATE TABLE IF NOT EXISTS quotes (
    id              SERIAL PRIMARY KEY,
    customer_id     INTEGER REFERENCES customers(id),
    agent_id        INTEGER REFERENCES agents(id),
    person_type     VARCHAR(10) DEFAULT 'personal',
    insured_name    VARCHAR(50) NOT NULL,
    jumin           VARCHAR(20),
    corp_name       VARCHAR(100),
    biz_no          VARCHAR(20),
    corp_no         VARCHAR(20),
    ceo_name        VARCHAR(50),
    phone           VARCHAR(20),
    prev_company    VARCHAR(20),
    prev_premium    INTEGER DEFAULT 0,
    driver_range    VARCHAR(30),
    age_limit       VARCHAR(20),
    driver_name     VARCHAR(50),
    driver_birth    VARCHAR(10),
    driver_gender   VARCHAR(5),
    car_code        VARCHAR(20),
    car_name        VARCHAR(100),
    car_number      VARCHAR(20),
    car_year        INTEGER,
    car_price       INTEGER DEFAULT 0,
    cc              INTEGER DEFAULT 0,
    car_grade       VARCHAR(20),
    people          VARCHAR(10),
    sports          VARCHAR(10),
    airbag          VARCHAR(5) DEFAULT '0',
    abs_yn          VARCHAR(5) DEFAULT '0',
    steal_yn        VARCHAR(5) DEFAULT '0',
    transmission    VARCHAR(5),
    fuel_type       VARCHAR(5),
    outset_date     VARCHAR(10),
    dambo_d2        VARCHAR(10),
    dambo_dm        VARCHAR(10),
    dambo_js        VARCHAR(10),
    dambo_mu        VARCHAR(10),
    dambo_jc        VARCHAR(10),
    dambo_em        VARCHAR(10),
    insurance_start VARCHAR(10),
    insurance_end   VARCHAR(10),
    career_ins      VARCHAR(10) DEFAULT 'B5',
    career_car      VARCHAR(10) DEFAULT 'B5',
    prev_3yr        VARCHAR(5) DEFAULT '4',
    halin_grade     VARCHAR(10) DEFAULT '13Z',
    traffic_code    VARCHAR(10) DEFAULT 'C012',
    traffic_count   INTEGER DEFAULT 0,
    car_count       INTEGER DEFAULT 1,
    muljuk          INTEGER DEFAULT 200,
    acci_3yr        INTEGER DEFAULT 0,
    acci_1yr        INTEGER DEFAULT 0,
    acci_score      INTEGER DEFAULT 0,
    discount_tags   JSONB DEFAULT '{}',
    map_type        VARCHAR(10) DEFAULT '0',
    map_score       VARCHAR(10) DEFAULT '0',
    mileage         VARCHAR(10) DEFAULT '0',
    hd_special      VARCHAR(10) DEFAULT 'h01',
    samsung_3yr     VARCHAR(10),
    meritz_3yr      VARCHAR(10) DEFAULT 'B5',
    parts_total     INTEGER DEFAULT 0,
    parts_detail    JSONB DEFAULT '{}',
    result_data     JSONB DEFAULT '[]',
    status          VARCHAR(20) DEFAULT 'draft',
    memo            TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_quotes_customer ON quotes(customer_id);
CREATE INDEX idx_quotes_status ON quotes(status);
CREATE INDEX idx_quotes_created ON quotes(created_at);

-- multi_quotes table (same policy multi vehicle)
CREATE TABLE IF NOT EXISTS multi_quotes (
    id              SERIAL PRIMARY KEY,
    customer_id     INTEGER REFERENCES customers(id),
    name            VARCHAR(100),
    quote_ids       JSONB DEFAULT '[]',
    result_data     JSONB DEFAULT '{}',
    status          VARCHAR(20) DEFAULT 'draft',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_multi_quotes_customer ON multi_quotes(customer_id);
